version: 3
image: debian:latest
stages:
- build
Production Build:
  label: latest
  stage: build
  job_type: image_build
  only:
    branches:
    - master
  build_dir: /
  cache: false
  dockerfile_path: /Dockerfile
